# Generated by Django 4.2.7 on 2025-01-16 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('englishWords', '0003_gamescore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamescore',
            old_name='date',
            new_name='created_at',
        ),
    ]
